### ISSUE TITLE
Help with install

### ISSUE THREAD

**Issue by ghost** [SaahilClaypool/pale-green#1]
I don't understand how to install this pale-green theme i really like it can you help ?

**Comment by SaahilClaypool** [comment]
Sure thing. I had removed the pale-green theme from the package earlier by mistake, but I have re-added it. 

You should be able to open the menu (ctrl+p / mac+p) and enter `ext install saahilclaypool.blind-themes`. 

After that, you can change your color theme to pale-green by going to settings and searching for the theme option. (there are a few other colors included which are listed in the readme). 

Hope that helps.
